version: "3"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    container_name: "drupal_env_mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    volumes:
      - ./docker-runtime/data/mariadb:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    ports:
      - "3306:3306"

  php:
    image: wodby/drupal-php:7.1-dev-4.5.2
    container_name: "drupal_env_php"
    environment:
      PHP_SITE_NAME: drupal-test
      PHP_HOST_NAME: localhost:8000
      PHP_DOCROOT: web # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
## Read instructions at https://wodby.com/stacks/drupal/docs/local/xdebug/
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ & Linux/Mac/Win
#      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux, Docker < 18.03
#      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS, Docker < 18.03
#      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows, Docker < 18.03
    volumes:
      - ./drupal:/var/www/html

  mailhog:
    image: mailhog/mailhog
    container_name: "drupal_env_mailhog"
    ports:
      - "10025:8025"

  nginx:
    image: wodby/drupal-nginx:1.0.0
    container_name: "drupal_env_nginx"
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: web # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
    volumes:
      - ./drupal:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "10099:80"
